from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PATHS = [
    ".editorconfig",
    ".gitattributes",
    ".github/workflows/project-checks.yml",
    "README.md",
    "LICENSE",
    "Makefile",
    "main.c",
    "include/audio.h",
    "include/board_config.h",
    "include/board_init.h",
    "include/display_assets.h",
    "include/game_state.h",
    "include/keypad.h",
    "include/lcd_driver.h",
    "include/timing.h",
    "src/audio.c",
    "src/board_init.c",
    "src/display_assets.c",
    "src/game_state.c",
    "src/keypad.c",
    "src/lcd_driver.c",
    "src/timing.c",
    "tests/test_game_state.c",
    "docs/ARCHITECTURE.md",
    "docs/QA.md",
    "nbproject/configurations.xml",
]

FORBIDDEN_PATHS = [
    "build",
    "dist",
    ".generated_files",
    "nbproject/private",
]

LINE_LIMITS = {
    "main.c": 220,
    "src/audio.c": 170,
    "src/game_state.c": 180,
    "src/keypad.c": 90,
    "src/lcd_driver.c": 90,
    "tests/test_game_state.c": 160,
}

SUSPICIOUS_TERMS = [
    "chat" + "gpt",
    "ai-" + "generated",
    "generated by " + "ai",
    "as an " + "ai",
    "god" + "file",
    "to" + "do",
    "fix" + "me",
    "place" + "holder",
    "dum" + "my",
    "tem" + "plate",
]


def fail(message):
    print(message)
    return 1


def has_comment_syntax(text):
    in_string = False
    in_char = False
    i = 0

    while i < len(text) - 1:
        current = text[i]
        next_char = text[i + 1]

        if in_string:
            if current == "\\":
                i += 2
                continue
            if current == '"':
                in_string = False
        elif in_char:
            if current == "\\":
                i += 2
                continue
            if current == "'":
                in_char = False
        else:
            if current == '"':
                in_string = True
            elif current == "'":
                in_char = True
            elif current == "/" and next_char in {"/", "*"}:
                return True

        i += 1

    return False


def scan_terms(path):
    text = path.read_text(encoding="utf-8", errors="ignore").lower()
    for term in SUSPICIOUS_TERMS:
        if term in text:
            return term

    return None


def main():
    for relative_path in REQUIRED_PATHS:
        if not (ROOT / relative_path).exists():
            return fail(f"Missing required path: {relative_path}")

    for relative_path in FORBIDDEN_PATHS:
        if (ROOT / relative_path).exists():
            return fail(f"Build output should not be committed: {relative_path}")

    for relative_path, max_lines in LINE_LIMITS.items():
        path = ROOT / relative_path
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        if len(lines) > max_lines:
            return fail(f"{relative_path} has {len(lines)} lines; limit is {max_lines}")

    source_roots = [ROOT / "main.c", ROOT / "src", ROOT / "include", ROOT / "tests"]
    for source_root in source_roots:
        paths = [source_root] if source_root.is_file() else source_root.rglob("*")
        for path in paths:
            if path.is_file() and path.suffix.lower() in {".c", ".h"}:
                text = path.read_text(encoding="utf-8", errors="ignore")
                if has_comment_syntax(text):
                    return fail(f"Comment syntax found in {path.relative_to(ROOT)}")
                term = scan_terms(path)
                if term is not None:
                    return fail(f"Suspicious term '{term}' found in {path.relative_to(ROOT)}")

    project = (ROOT / "nbproject" / "configurations.xml").read_text(encoding="utf-8", errors="ignore")
    for relative_path in ["src/game_state.c", "include/game_state.h", "include/board_config.h"]:
        if relative_path not in project:
            return fail(f"MPLAB project metadata does not reference {relative_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
